### ISSUE TITLE
"HTTP request failed" when using hardware wallet with MetaMask and trying to download a file from an existing dataset

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/commons#85]
This issue was [reported by @TheStroj on Gitter](https://gitter.im/oceanprotocol/Lobby?at=5cab8526759abc043c8a24de):

> Hey guys, wanted to provide some feedback and ask some questions about the commons marketplace:
>
> 1) Using a hardware wallet account (in MetaMask), I get the "HTTP request failed" error when trying to download a file from an existing dataset. When trying to publish a dataset with that account, it seems to be stuck on the signing loading wheel.

**Comment by kremalicious** [comment]
what hardware wallet?

**Comment by TheStroj** [comment]
The wallet I'm having this issue with is a Trezor One (newest stable firmware, version 1.8.0).

**Comment by TheStroj** [comment]
Interestingly, I get a MetaMask confirmation (containing the transaction info, including transaction price and gas fee) after I get the HTTP error, but nothing happens afterwards (not even one hour later).

**Comment by kremalicious** [comment]
Hey @TheStroj, would you be able to test this again with your setup? We deployed many changes in the last days around the consuming process and this issue here might have been fixed too. Thanks!

**Comment by TheStroj** [comment]
Tested three different dataset files, and one worked, two didn't - still the same error as before ("HTTP request failed"). Tried waiting for half an hour, but didn't go through. As before, I get a MetaMask confirmation (containing the transaction info, including transaction price and gas fee) after I get the HTTP error, but now I also get an extra confirmation after the HTTP error (the one labelled Contract Interaction). So I get the HTTP error, then soon after the first confirmation, and then after a while also the second one (whereas before, I only got the first confirmation after the error).

**Comment by jernejpregelj** [comment]
@TheStroj Can you verify if this error is happening with all accounts from hardware wallet or there is no difference between ones with hardware wallet and non-hardware wallet.

**Comment by TheStroj** [comment]
Tried to do things a bit more systematically this time. I tested 4 different datasets, and downloaded the first file for each of them, with both the hardware and non-hardware wallets:

1) https://commons.oceanprotocol.com/asset/did:op:091dc3b04aad459ea7a59ad152ddbe184ae2b2b3837c4879abe56fcc3a2af377
Hardware: HTTP request failed (once), Error consuming assets (multiple times)
Non-hardware: HTTP request failed (once), Error consuming assets (multiple times)

2) https://commons.oceanprotocol.com/asset/did:op:0e2f45bfc79d450c955a677db521c238b201eae30dcf44979e1d6ad337d761b3
Hardware: HTTP request failed (once), Error consuming assets (multiple times)
Non-hardware: Error consuming assets (multiple times)

3) https://commons.oceanprotocol.com/asset/did:op:2f9624ab05764a5e8f9727fb660cad77505d86d8f8e14c408d2b6098912d3097
Hardware: works
Non-hardware: HTTP request failed (multiple times), works

4) https://commons.oceanprotocol.com/asset/did:op:b3bb62769a3d4d52960a2390ff33eb6319b324519c7b4509b3bfb9a3bcbafb68
Hardware: works
Non-hardware: works

Observations:
- Apart from the occasional "HTTP request failed" error, there doesn't seem to be any difference between hardware and non-hardware wallets for all 4 datasets. So the errors could indeed be the same as #86.
- Datasets 1 and 2 throw the "Error consuming assets" after 4 confirmations (tested at least twice for all variations).
- Datasets 3 and 4 work as intented.
- Occasionally, I got a "HTTP request failed" for 3 of the 4 datasets, but then the next time it would go back to the "Error consuming assets" error (for datasets 1 and 2) or to working normally (for dataset 3). Every time it would happen just once, with the exception of dataset 3 with a non-hardware account, where it happened multiple times in a row - after 3 tries, it started working though. So I couldn't effectively replicate the error - it seemed to appear randomly as I was testing.

**Comment by jernejpregelj** [comment]
1. This asset fails every time for me (worked 0/5 tries). Could be that remote file is not there anymore and Brizo is failling to retrieve it. Solution would be to do periodic health checks on assets and provide clear error message to the user.
2. Works (3/5 tries)
3. Works (4/5 tries)
4. Works (5/5 tries)

There are still random failures on consume flow that we are resolving and are tied to stability of network or services.

I did not detect any difference between hardware wallet or not using hardware wallet. So I will be closing this issue and add comments on thread about consume files (https://github.com/oceanprotocol/commons/issues/86)
