### ISSUE TITLE
Downloading a dataset file sometimes doesn't go through

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/commons#86]
This issue was [reported by @TheStroj on Gitter](https://gitter.im/oceanprotocol/Lobby?at=5cab8526759abc043c8a24de):

> 4) With the regular account [i.e. not a hardware wallet], downloading a dataset file sometimes doesn't go through (remains on "Decrypting file, please sign..."), even after going through all the confirmations from 3) and waiting for about 20 minutes.

### Errors investigation & fixing

From https://github.com/oceanprotocol/commons/issues/86#issuecomment-482510812:

- [x] **HTTP request failed**: shortly after clicking the button, Brizo returns 401 Unauthorized status on `/services/access/initialize` and says “Failed to create agreement“ in console. squid-js and UI show “HTTP request failed”
- [x] **HTTP request failed**: `Error: argument of type 'NoneType' is not iterable`
- [ ] **Error consuming assets**: `Error getting the url content: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))` from Brizo in console shortly before file consuming starts, squid-js and UI show “Error consuming assets”
- [x] **Error consuming assets**: “Requested DID is not found in the keeper network” from Brizo in console after first signature while consuming, squid-js and UI show “Error consuming assets” (https://github.com/oceanprotocol/squid-js/issues/200)
- [x] doesn't continue after "Payment OK", just hangs
- [x] when all goes through from Brizo, getting `n.headers.get(...) is null` in console

**Comment by TheStroj** [comment]
This is the dataset that I'm having this issue with: https://commons.oceanprotocol.com/asset/did:op:db6cd93d6820406f9d4dc5c9f6fb53131a9a6eebe6784a9aa0a8e9c066f4537c

Tried it again just now, got the same result. I initiated the request at 18:44 - I can see only two relevant transactions in my MetaMask history (one "Approve" and one "Contract Interaction"), and at 19:16 I can still see the "Decrypting file URL, please sign..." message. This is with the normal (non-hardware protected) MetaMask account.

**Comment by kremalicious** [comment]
Excellent, thanks for the details!

**Comment by TheStroj** [comment]
Update: left everything open and I got another confirmation from MetaMask at 19:39 (so 55 minutes after the request was made), and after that the dataset request went through. So the file downloads eventually, the issue is just that it takes a long time to do it.

**Comment by kremalicious** [comment]
For me it always hangs after console message `Payment was OK`, and when waiting long enough it eventually goes through. 

This means in squid-js it's hanging on this line: https://github.com/oceanprotocol/squid-js/blob/a32435b85359ce690c3f28b17d7324c1032b5a91/src/ocean/OceanAssets.ts#L241

**Comment by kremalicious** [comment]
So after lots of testing and tweaking in squid-js we run consistently into 3 different errors. We already have some fixes making the flow way quicker (between "Payment OK" & "Access granted") in https://github.com/oceanprotocol/squid-js/pull/191 and use this for testing with commons against https://nginx-aquarius.dev-ocean.com (v0.2.2) & https://nginx-brizo.dev-ocean.com (v0.3.4). 

The errors:

1. HTTP request error shortly after clicking the button, Brizo returns `401 Unauthorized` status on `/services/access/initialize` and says “Failed to create agreement“. squid-js and UI show “HTTP request failed”
2. “Connection Aborted” from Brizo shortly before file consuming starts, squid-js and UI show “Error consuming assets”
3. when all goes through from Brizo, getting `n.headers.get(...) is null`. But file is actually there as the final response, when copying the returned consume url and accessing it directly, file downloads as expected with proper file name and all.

From squid-js side, we're not sure why 3 happens but this seems solvable on squid-js side. The other 2 errors need more investigation on the Brizo side.

**Comment by kremalicious** [comment]
Error no.3 is also on Brizo side and a fix is already merged https://github.com/oceanprotocol/brizo/pull/126

**Comment by with-draw** [comment]
I reported this issue on Gitter, and it seems to be related to this thread. I'm not sure if the amendments have been published yet, because I'm not a developer and Github is completely new to me. Either way, documenting it here.

![image](https://user-images.githubusercontent.com/48666714/56121255-52ccb980-5fa2-11e9-9b70-24031d0a5286.png)

**Comment by kremalicious** [comment]
We have deployed various fixes in brizo, squid-js, and commons making the consume flow much more faster and reliable, among other things:

- fix hanging consume flow
- set original filename at end of flow
- way faster Ocean initiating

Would be great if everyone who ran into the hanging consume flow could test again.

Occasionally, we still run into the 2 unticked errors in issue description so we'll keep this issues open for now

**Comment by TheStroj** [comment]
Tested three different dataset / notebook files (including the problematic one from my first comment) and it worked like a charm for all three of them. Also much faster than when it was working properly before (1 to 3 minutes for each of them). Great job guys!

I did run into the issue where I got the "Error consuming assets" error when I first tried downloading the CIFAR-100 dataset I uploaded (this error appeared after doing all the necessary MetaMask confirmations). But when I tried again immediately afterwards, it downloaded the file with no issues, so I couldn't reproduce it. For reference, it was this dataset:
https://commons.oceanprotocol.com/asset/did:op:091dc3b04aad459ea7a59ad152ddbe184ae2b2b3837c4879abe56fcc3a2af377

**Comment by jernejpregelj** [comment]
Managed to replicate error with `brizo/initialize 422 (UNPROCESSABLE ENTITY)`:
Start publish process and then fail/cancel last signature/transaction. That will complete flow where you can still see asset over search but will fail with error while trying to consume.

**Comment by aaitor** [comment]
A different but related issue, the flow is stuck showing the message "Decrypting file URL, please sign...
": https://github.com/oceanprotocol/commons/issues/132

**Comment by ssallam** [comment]
It seems that the last issue above was caused by deployment of a recent version of Brizo to the Nile network unintentionally which is not compatible with the current commons marketplace.

**Comment by kremalicious** [comment]
After numerous fixes and improvements in the last weeks in pretty much all the components the consume flow is now in a stable state. We are not running into any of the above errors anymore, and provide more feedback during all network interactions.
